apiVersion: apps/v1
kind: Deployment
metadata:
  name: details-nodejs
spec:
  selector:
    matchLabels:
      app: details-nodejs
  template:
    metadata:
      labels:
        app: details-nodejs
    spec:
      containers:
        - name: details-nodejs
          image: de.icr.io/kmddk/aai-bookinfo-details-v2:1.0
          ports:
            - containerPort: 3000
          env:
            - name: LOG_LEVEL
              value: "debug"